### ISSUE TITLE
创建bean copy 代理对象失败:

### ISSUE THREAD

**Issue by qq517634644** [zhou-hao/hsweb4-examples#1]
`
public void copy(Object s, Object t, java.util.Set ignore, org.hswebframework.web.bean.Converter converter){
try{
	org.hswebframework.web.starter.initialize.SystemVersion $$__source=(org.hswebframework.web.starter.initialize.SystemVersion)s;
	java.util.Map $$__target=(java.util.Map)t;
	if(!ignore.contains("website")){
	if($$__source.getWebsite()!=null){
java.lang.Object website=(java.lang.Object)(converter.convert((Object)($$__source.getWebsite()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(website!=null){
	$$__target.put("website",website);
	}
	}
}
if(!ignore.contains("revisionVersion")){
	java.lang.Object revisionVersion=(java.lang.Object)(converter.convert((Object)(Integer.valueOf($$__source.getRevisionVersion())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(revisionVersion!=null){
	$$__target.put("revisionVersion",revisionVersion);
	}
}
if(!ignore.contains("name")){
	if($$__source.getName()!=null){
java.lang.Object name=(java.lang.Object)(converter.convert((Object)($$__source.getName()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(name!=null){
	$$__target.put("name",name);
	}
	}
}
if(!ignore.contains("comment")){
	if($$__source.getComment()!=null){
java.lang.Object comment=(java.lang.Object)(converter.convert((Object)($$__source.getComment()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(comment!=null){
	$$__target.put("comment",comment);
	}
	}
}
if(!ignore.contains("majorVersion")){
	java.lang.Object majorVersion=(java.lang.Object)(converter.convert((Object)(Integer.valueOf($$__source.getMajorVersion())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(majorVersion!=null){
	$$__target.put("majorVersion",majorVersion);
	}
}
if(!ignore.contains("minorVersion")){
	java.lang.Object minorVersion=(java.lang.Object)(converter.convert((Object)(Integer.valueOf($$__source.getMinorVersion())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(minorVersion!=null){
	$$__target.put("minorVersion",minorVersion);
	}
}
if(!ignore.contains("snapshot")){
	java.lang.Object snapshot=(java.lang.Object)(converter.convert((Object)(Boolean.valueOf($$__source.isSnapshot())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(snapshot!=null){
	$$__target.put("snapshot",snapshot);
	}
}
if(!ignore.contains("frameworkVersion")){
	if($$__source.getFrameworkVersion()!=null){
java.lang.Object frameworkVersion=(java.lang.Object)(converter.convert((Object)($$__source.getFrameworkVersion()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(frameworkVersion!=null){
	$$__target.put("frameworkVersion",frameworkVersion);
	}
	}
}
if(!ignore.contains("dependencies")){
	if($$__source.getDependencies()!=null){
java.lang.Object dependencies=(java.lang.Object)(converter.convert((Object)($$__source.getDependencies()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
	if(dependencies!=null){
	$$__target.put("dependencies",dependencies);
	}
	}
}
}catch(Exception e){
	throw new RuntimeException(e.getMessage(),e);
}

}

java.lang.NullPointerException: Cannot invoke "java.lang.reflect.AccessibleObject.setAccessible(boolean)" because "ao" is null
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103) ~[javassist-3.22.0-GA.jar:na]
	at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151) ~[javassist-3.22.0-GA.jar:na]
	at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134) ~[javassist-3.22.0-GA.jar:na]
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95) ~[javassist-3.22.0-GA.jar:na]
	at javassist.ClassPool.toClass(ClassPool.java:1143) ~[javassist-3.22.0-GA.jar:na]
	at javassist.CtClass.toClass(CtClass.java:1316) ~[javassist-3.22.0-GA.jar:na]
	at org.hswebframework.web.proxy.Proxy.getTargetClass(Proxy.java:156) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.proxy.Proxy.newInstance(Proxy.java:150) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:170) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.lambda$getCopier$0(FastBeanCopier.java:137) ~[hsweb-core-4.0.9.jar:na]
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[na:na]
	at org.hswebframework.web.bean.FastBeanCopier.getCopier(FastBeanCopier.java:137) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:113) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:99) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:90) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.starter.initialize.SystemInitialize.syncSystemVersion(SystemInitialize.java:78) ~[hsweb-starter-4.0.9.jar:na]
	at org.hswebframework.web.starter.initialize.SystemInitialize.install(SystemInitialize.java:211) ~[hsweb-starter-4.0.9.jar:na]
	at org.hswebframework.web.starter.HswebAutoConfiguration.lambda$systemInit$2(HswebAutoConfiguration.java:72) ~[hsweb-starter-4.0.9.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.hswebframework.example.crud.CrudApplication.main(CrudApplication.java:21) ~[classes/:na]

2021-03-26 14:40:06.467  INFO 25396 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-26 14:40:06.471 ERROR 25396 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.hswebframework.example.crud.CrudApplication.main(CrudApplication.java:21) ~[classes/:na]
Caused by: java.lang.UnsupportedOperationException: Cannot invoke "java.lang.reflect.AccessibleObject.setAccessible(boolean)" because "ao" is null
	at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:173) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.lambda$getCopier$0(FastBeanCopier.java:137) ~[hsweb-core-4.0.9.jar:na]
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[na:na]
	at org.hswebframework.web.bean.FastBeanCopier.getCopier(FastBeanCopier.java:137) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:113) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:99) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:90) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.starter.initialize.SystemInitialize.syncSystemVersion(SystemInitialize.java:78) ~[hsweb-starter-4.0.9.jar:na]
	at org.hswebframework.web.starter.initialize.SystemInitialize.install(SystemInitialize.java:211) ~[hsweb-starter-4.0.9.jar:na]
	at org.hswebframework.web.starter.HswebAutoConfiguration.lambda$systemInit$2(HswebAutoConfiguration.java:72) ~[hsweb-starter-4.0.9.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	... 5 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.AccessibleObject.setAccessible(boolean)" because "ao" is null
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103) ~[javassist-3.22.0-GA.jar:na]
	at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151) ~[javassist-3.22.0-GA.jar:na]
	at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134) ~[javassist-3.22.0-GA.jar:na]
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95) ~[javassist-3.22.0-GA.jar:na]
	at javassist.ClassPool.toClass(ClassPool.java:1143) ~[javassist-3.22.0-GA.jar:na]
	at javassist.CtClass.toClass(CtClass.java:1316) ~[javassist-3.22.0-GA.jar:na]
	at org.hswebframework.web.proxy.Proxy.getTargetClass(Proxy.java:156) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.proxy.Proxy.newInstance(Proxy.java:150) ~[hsweb-core-4.0.9.jar:na]
	at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:170) ~[hsweb-core-4.0.9.jar:na]
	... 15 common frames omitted

`

**Comment by zhou-hao** [comment]
用java8试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tensai ***@***.***&gt;
发送时间: 2021年3月26日 14:43
收件人: zhou-hao/hsweb4-examples ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[zhou-hao/hsweb4-examples] 创建bean copy 代理对象失败: (#1)





 
`
 public void copy(Object s, Object t, java.util.Set ignore, org.hswebframework.web.bean.Converter converter){
 try{
 org.hswebframework.web.starter.initialize.SystemVersion $$__source=(org.hswebframework.web.starter.initialize.SystemVersion)s;
 java.util.Map $$__target=(java.util.Map)t;
 if(!ignore.contains("website")){
 if($$__source.getWebsite()!=null){
 java.lang.Object website=(java.lang.Object)(converter.convert((Object)($$__source.getWebsite()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(website!=null){
 $$__target.put("website",website);
 }
 }
 }
 if(!ignore.contains("revisionVersion")){
 java.lang.Object revisionVersion=(java.lang.Object)(converter.convert((Object)(Integer.valueOf($$__source.getRevisionVersion())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(revisionVersion!=null){
 $$__target.put("revisionVersion",revisionVersion);
 }
 }
 if(!ignore.contains("name")){
 if($$__source.getName()!=null){
 java.lang.Object name=(java.lang.Object)(converter.convert((Object)($$__source.getName()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(name!=null){
 $$__target.put("name",name);
 }
 }
 }
 if(!ignore.contains("comment")){
 if($$__source.getComment()!=null){
 java.lang.Object comment=(java.lang.Object)(converter.convert((Object)($$__source.getComment()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(comment!=null){
 $$__target.put("comment",comment);
 }
 }
 }
 if(!ignore.contains("majorVersion")){
 java.lang.Object majorVersion=(java.lang.Object)(converter.convert((Object)(Integer.valueOf($$__source.getMajorVersion())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(majorVersion!=null){
 $$__target.put("majorVersion",majorVersion);
 }
 }
 if(!ignore.contains("minorVersion")){
 java.lang.Object minorVersion=(java.lang.Object)(converter.convert((Object)(Integer.valueOf($$__source.getMinorVersion())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(minorVersion!=null){
 $$__target.put("minorVersion",minorVersion);
 }
 }
 if(!ignore.contains("snapshot")){
 java.lang.Object snapshot=(java.lang.Object)(converter.convert((Object)(Boolean.valueOf($$__source.isSnapshot())),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(snapshot!=null){
 $$__target.put("snapshot",snapshot);
 }
 }
 if(!ignore.contains("frameworkVersion")){
 if($$__source.getFrameworkVersion()!=null){
 java.lang.Object frameworkVersion=(java.lang.Object)(converter.convert((Object)($$__source.getFrameworkVersion()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(frameworkVersion!=null){
 $$__target.put("frameworkVersion",frameworkVersion);
 }
 }
 }
 if(!ignore.contains("dependencies")){
 if($$__source.getDependencies()!=null){
 java.lang.Object dependencies=(java.lang.Object)(converter.convert((Object)($$__source.getDependencies()),java.lang.Object.class,org.hswebframework.web.bean.FastBeanCopier.EMPTY_CLASS_ARRAY));
 if(dependencies!=null){
 $$__target.put("dependencies",dependencies);
 }
 }
 }
 }catch(Exception e){
 throw new RuntimeException(e.getMessage(),e);
 }
 
}
 
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.AccessibleObject.setAccessible(boolean)" because "ao" is null
 at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103) ~[javassist-3.22.0-GA.jar:na]
 at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151) ~[javassist-3.22.0-GA.jar:na]
 at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134) ~[javassist-3.22.0-GA.jar:na]
 at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95) ~[javassist-3.22.0-GA.jar:na]
 at javassist.ClassPool.toClass(ClassPool.java:1143) ~[javassist-3.22.0-GA.jar:na]
 at javassist.CtClass.toClass(CtClass.java:1316) ~[javassist-3.22.0-GA.jar:na]
 at org.hswebframework.web.proxy.Proxy.getTargetClass(Proxy.java:156) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.proxy.Proxy.newInstance(Proxy.java:150) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:170) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.lambda$getCopier$0(FastBeanCopier.java:137) ~[hsweb-core-4.0.9.jar:na]
 at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[na:na]
 at org.hswebframework.web.bean.FastBeanCopier.getCopier(FastBeanCopier.java:137) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:113) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:99) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:90) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.starter.initialize.SystemInitialize.syncSystemVersion(SystemInitialize.java:78) ~[hsweb-starter-4.0.9.jar:na]
 at org.hswebframework.web.starter.initialize.SystemInitialize.install(SystemInitialize.java:211) ~[hsweb-starter-4.0.9.jar:na]
 at org.hswebframework.web.starter.HswebAutoConfiguration.lambda$systemInit$2(HswebAutoConfiguration.java:72) ~[hsweb-starter-4.0.9.jar:na]
 at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.hswebframework.example.crud.CrudApplication.main(CrudApplication.java:21) ~[classes/:na]
 
2021-03-26 14:40:06.467  INFO 25396 --- [           main] ConditionEvaluationReportLoggingListener :
 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
 2021-03-26 14:40:06.471 ERROR 25396 --- [           main] o.s.boot.SpringApplication               : Application run failed
 
java.lang.IllegalStateException: Failed to execute CommandLineRunner
 at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 at org.hswebframework.example.crud.CrudApplication.main(CrudApplication.java:21) ~[classes/:na]
 Caused by: java.lang.UnsupportedOperationException: Cannot invoke "java.lang.reflect.AccessibleObject.setAccessible(boolean)" because "ao" is null
 at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:173) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.lambda$getCopier$0(FastBeanCopier.java:137) ~[hsweb-core-4.0.9.jar:na]
 at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[na:na]
 at org.hswebframework.web.bean.FastBeanCopier.getCopier(FastBeanCopier.java:137) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:113) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:99) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.copy(FastBeanCopier.java:90) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.starter.initialize.SystemInitialize.syncSystemVersion(SystemInitialize.java:78) ~[hsweb-starter-4.0.9.jar:na]
 at org.hswebframework.web.starter.initialize.SystemInitialize.install(SystemInitialize.java:211) ~[hsweb-starter-4.0.9.jar:na]
 at org.hswebframework.web.starter.HswebAutoConfiguration.lambda$systemInit$2(HswebAutoConfiguration.java:72) ~[hsweb-starter-4.0.9.jar:na]
 at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
 ... 5 common frames omitted
 Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.AccessibleObject.setAccessible(boolean)" because "ao" is null
 at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103) ~[javassist-3.22.0-GA.jar:na]
 at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151) ~[javassist-3.22.0-GA.jar:na]
 at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134) ~[javassist-3.22.0-GA.jar:na]
 at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95) ~[javassist-3.22.0-GA.jar:na]
 at javassist.ClassPool.toClass(ClassPool.java:1143) ~[javassist-3.22.0-GA.jar:na]
 at javassist.CtClass.toClass(CtClass.java:1316) ~[javassist-3.22.0-GA.jar:na]
 at org.hswebframework.web.proxy.Proxy.getTargetClass(Proxy.java:156) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.proxy.Proxy.newInstance(Proxy.java:150) ~[hsweb-core-4.0.9.jar:na]
 at org.hswebframework.web.bean.FastBeanCopier.createCopier(FastBeanCopier.java:170) ~[hsweb-core-4.0.9.jar:na]
 ... 15 common frames omitted
 
`
